# Air Configuration File for Nebula Backend

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/server/main.go && ./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "data", "cmd/server/tmp", "cmd/server/data"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["api", "cmd", "config", "internal"]
  include_ext = ["go", "tpl", "tmpl", "html", "toml", "yaml", "json", "env"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  main = "\x1b[34;1m"   # Blue and bold
  watcher = "\x1b[32m"  # Green
  build = "\x1b[33m"    # Yellow
  runner = "\x1b[35m"   # Magenta
  app = "\x1b[36m"      # Cyan

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true

[proxy]
  app_port = 8080
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = false
